version: '2.1'
services:
  db:
    image: hexanyn/boxbot_postgres
    volumes:
    - './db/data:/var/lib/postgresql/data'
    env_file: boxbot.env
    restart: always

  bot:
    image: hexanyn/boxbot_python
    volumes:
    - ./bot:/data
    - /data/dhcp/data:/dhcp
    env_file: boxbot.env
    restart: always
