version: '2.1'
services:
  db:
    image: postgres:12.1
    container_name: boxbot_db
    volumes:
    - ./db:/var/lib/postgresql/data
    env_file: boxbot.env
    restart: always

  bot:
    image: hexanyn/boxbot
    container_name: boxbot
    volumes:
    - ./bot:/data
    - /data/dhcp/data:/dhcp
    - /data/bind9/bind/lib:/dns
    - /data/ssh/config/.ssh/authorized_keys:/ssh/authorized_keys
    depends_on:
    - db
    env_file: boxbot.env
    restart: always
